version: '2'

services:

  datastore:
    image: busybox
    volumes:
      - mysql2-data:/var/lib/mysql
      - redis-data:/data
      - bundle_install:/app/vendor/bundle
      - bundle:${PWD}/.bundle
      - node_modules:${PWD}/node_modules

  db:
    image: mysql:5.7.10
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=root
      - MYSQL_DATABASE=website-design_sandbox_development
    ports:
      - "13306:3306"
    volumes_from:
      - datastore

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes_from:
      - datastore
    command: redis-server

volumes:
  mysql2-data:
    driver: local
  redis-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
